---
- hosts: localhost
  gather_facts:  no

  tasks:
    - name: "Read Host info from CSV file and return a list"
      read_csv:
        path: test.csv
        fieldnames: VMName,ip
        delimiter: ','
      register: hostinfo

    - include_tasks: create_ports.yml
      loop: "{{ hostinfo.list[1:] }}"
